<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRdusxs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRdusxs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRdusxs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRdusxs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSRdusxs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SRdusxs',
    'container.build_id' => '0ff637be',
    'container.build_time' => 1641134282,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRdusxs');
